import { useEffect, useMemo, useState } from 'react'
import { useAppStore } from '../hooks/useAppStore'
import { useLiveClock } from '../hooks/useLiveClock'
import { expectedOutcomeFor } from '../mock/mockData'
import { recommend as pickRecommendation, fetchCandidates } from '../services/optimizerService'
import Panel from '../components/ui/Panel'
import ConfirmDialog from '../components/ui/ConfirmDialog'
import { DataBadge, StatusBadge } from '../components/ui/Badges'
import { Spinner, IconChip, EmptyNote } from '../components/ui/Misc'
import { timeAgo } from '../utils/format'
import { IconArrowDown, IconArrowUp, IconBolt, IconCheck, IconClose } from '../components/icons'

function EffectChip({ text }) {
  const up = text.includes('↑')
  const down = text.includes('↓')
  const color = up ? '#3dffa8' : down ? '#ffb454' : '#8fa8b0'
  return (
    <span className="inline-flex items-center gap-1.5 rounded-md border px-2.5 py-1 font-mono text-[10px] tracking-wider"
      style={{ color, borderColor: `${color}44`, background: `${color}0f` }}
    >
      {up && <IconArrowUp size={11} />}
      {down && <IconArrowDown size={11} />}
      {text}
    </span>
  )
}

export default function ActionCenterPage() {
  const { zones, lastActions, runAction, notify, selectedZone } = useAppStore()
  const now = useLiveClock(1000)
  const [busy, setBusy] = useState(false)
  const [dismissed, setDismissed] = useState(false)
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [candidates, setCandidates] = useState(null)

  const zoneId = selectedZone === 'all' ? 'A' : selectedZone
  const z = zones?.[zoneId]

  useEffect(() => {
    let alive = true
    setCandidates(null)
    const zz = zones?.[zoneId]
    if (zz) {
      fetchCandidates(zones, zoneId).then((c) => alive && setCandidates(c))
    }
    return () => {
      alive = false
    }
  }, [zoneId, zones === null])

  useEffect(() => {
    setDismissed(false)
  }, [zoneId])

  const recommendation = useMemo(() => (candidates ? pickRecommendation(candidates) : null), [candidates])

  if (!z) return null

  const outcome = recommendation ? expectedOutcomeFor(recommendation.deviceStates) : null
  const pending = recommendation && !dismissed

  const applyRecommendation = async () => {
    setConfirmOpen(false)
    setBusy(true)
    await runAction({
      zoneId,
      label: recommendation.label,
      deviceStates: recommendation.deviceStates,
      source: 'uice',
    })
    setBusy(false)
    setDismissed(true)
  }

  const cancelRecommendation = () => {
    setDismissed(true)
    notify({ severity: 'info', title: 'Recommendation dismissed', message: `The suggestion "${recommendation.label}" was cancelled — no changes applied.` })
  }

  return (
    <div className="space-y-3 rise-in">
      <div className="grid grid-cols-1 xl:grid-cols-12 gap-3">
        <Panel title="Recommended Action" subtitle={`Generated by UICE from live Zone ${zoneId} state`} className="xl:col-span-7" corners>
          {!candidates ? (
            <div className="flex items-center justify-center gap-2 py-10 text-dim text-xs font-tech">
              <Spinner size={14} /> EVALUATING CANDIDATES…
            </div>
          ) : pending ? (
            <div className="rounded-xl border border-neon/30 bg-gradient-to-br from-neon/[0.08] to-transparent p-5 relative overflow-hidden">
              <div className="absolute -top-10 -right-10 w-40 h-40 rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle, rgba(61,255,168,.14), transparent 70%)' }} />
              <div className="flex items-start gap-4">
                <IconChip icon={IconBolt} color="#3dffa8" size={46} />
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="font-mono font-bold text-[19px] tracking-wide text-ink">{recommendation.label} — Zone {zoneId}</h3>
                    <DataBadge kind="estimated" dotted={false} />
                  </div>
                  <p className="mt-1.5 text-[12px] text-dim leading-relaxed">
                    Expected outcome: {outcome.primary}
                  </p>
                  <div className="mt-3 flex flex-wrap gap-2">
                    {outcome.effects.map((e) => (
                      <EffectChip key={e} text={e} />
                    ))}
                  </div>
                </div>
              </div>
              <div className="mt-5 flex items-center gap-2.5">
                <button type="button" className="btn btn-primary flex-1 sm:flex-none sm:min-w-[220px]" onClick={() => setConfirmOpen(true)} disabled={busy}>
                  {busy ? (<><Spinner size={13} color="#04261a" /> APPLYING…</>) : (<><IconCheck size={14} /> APPLY RECOMMENDATION</>)}
                </button>
                <button type="button" className="btn btn-ghost" onClick={cancelRecommendation} disabled={busy}>
                  <IconClose size={12} /> CANCEL
                </button>
              </div>
            </div>
          ) : (
            <EmptyNote>
              No pending recommendation. New suggestions appear when UICE detects an optimization opportunity.
            </EmptyNote>
          )}

          <div className="mt-4 grid grid-cols-3 gap-2.5">
            {[
              { label: 'Temperature', value: `${z.temperature.toFixed(1)} °C` },
              { label: 'Occupancy', value: `${z.occupancy}` },
              { label: 'Est. Power', value: `${z.estimatedPower} W` },
            ].map((s) => (
              <div key={s.label} className="rounded-lg border border-white/[0.06] bg-black/25 px-3 py-2 text-center">
                <div className="label-cap !text-[7.5px]">{s.label}</div>
                <div className="font-mono font-bold tnum text-[15px] text-ink mt-1">{s.value}</div>
              </div>
            ))}
          </div>
        </Panel>

        <Panel title="Action Log" subtitle="Most recent control actions across zones" className="xl:col-span-5">
          {lastActions.length === 0 ? (
            <EmptyNote>No actions applied yet in this session.</EmptyNote>
          ) : (
            <div className="space-y-2 max-h-[340px] overflow-y-auto pr-1">
              {lastActions.map((a) => (
                <div key={a.id} className="flex items-center gap-3 rounded-lg border border-white/[0.05] bg-black/25 px-3 py-2.5 hover:border-neon/25 transition-colors">
                  <span className="w-1.5 h-8 rounded-full shrink-0" style={{ background: a.source === 'manual' ? '#ffb454' : '#3dffa8', boxShadow: `0 0 8px ${a.source === 'manual' ? '#ffb45466' : '#3dffa866'}` }} />
                  <div className="min-w-0 flex-1">
                    <div className="text-[12.5px] font-semibold text-ink truncate">{a.label}</div>
                    <div className="font-mono text-[9px] tracking-[0.16em] text-faint uppercase mt-0.5">
                      ZONE {a.zoneId} · {timeAgo(a.ts, now.getTime())} · {a.source}
                    </div>
                  </div>
                  <StatusBadge level="ok" label="OK" />
                </div>
              ))}
            </div>
          )}
        </Panel>
      </div>

      <ConfirmDialog
        open={confirmOpen}
        title={`Apply "${recommendation?.label}"?`}
        message={`This will dispatch the control command to Zone ${zoneId}. Expected effect: ${outcome?.primary}. The action is executed through the service abstraction and currently resolves against the mock bus.`}
        confirmLabel="Apply Action"
        busy={busy}
        onConfirm={applyRecommendation}
        onCancel={() => setConfirmOpen(false)}
      />
    </div>
  )
}
